# Generated by Django 2.0.1 on 2018-01-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('retail_price', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=150)),
                ('source', models.CharField(blank=True, default='', max_length=150)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='api.Artist')),
            ],
        ),
    ]
